### ISSUE TITLE
Putting Numbers into Variables for TitleAndSubtitle Effect

### ISSUE THREAD

**Issue by Techno3600** [TheLimeGlass/Skellett#1]
Hello,

Hope you've been having a good day! My idea is pretty much explained here. It would be cool if we were able to do this!

My Syntax of TitleandSubtitle
- show title %string% and %-string% to %players% for %timespan% , %timespan% , %timespan%

command /testana:
	trigger:
		set {function.ana.1} to "&c&lTESTING"
		set {function.ana.2} to "&a&lFUCTIONS"
		set {function.ana.3} to "50 ticks"
		set {function.ana.4} to "30 ticks"
		set {function.ana.5} to "10 ticks"
		make player execute command "/ana"
command /ana:
	permission: test.admin
	permission message: &9Permissions> &7This requires Permission Rank [&9ADMIN&7].
	trigger:
		show title "%{function.ana.1}%" and "%{function.ana.2}%" to all players for {function.ana.3} , "function.ana.4} , {function.ana.5}

Thanks
Techno

**Comment by TheLimeGlass** [comment]
You already can, you can view the syntax.yml for the title/subtitle syntax
