### ISSUE TITLE
Gravitational State not working

### ISSUE THREAD

**Issue by xBiscuit** [TheLimeGlass/Skellett#10]
Tried gravitational state "gravity [state] [of] [entit(y|ies)] %entitys%" but it shows up as non existent. I have the most recent Skellett and Spigot server.
Thanks.
- xBiscuit

**Comment by TheLimeGlass** [comment]
Unable to reproduce error.

My testing setup: 1.11.2 spigot, Skellett 1.7 and a 1.8 client

Make sure your syntax matches this
```
gravity [state] [(of|for)] [entit(y|ies)] %entities%
```

Example script used:
```
on damage of pig:
	broadcast "%gravity state of victim%"
	set gravity state of victim to false
	broadcast "%gravity state of victim%"
```
