### ISSUE TITLE
loop-enchantment issue

### ISSUE THREAD

**Issue by BetaBurnt** [TheLimeGlass/Skellett#101]
`loop-enchantment` broken as of Skellett 1.9.9. In 1.9.8 this basic Skript works fine:

> command /test:
>   trigger:
>     loop enchantments of player's tool:
>       broadcast "%loop-enchantment%"

However on updating to Skellett 1.9.9 it no longer recognises `loop-enchantment` as a valid thing. If this is one of the things that was removed because it's been moved to base Skript, it shouldn't have been or what was moved over to base Skript is broken/not the same either, as it only recognises `loop-value` when looping enchantments of an item in base Skript which does not output the same information `loop-enchantment` did.

The `remove 1 from level of loop-enchantment of <item>` feature is also broken, possibly/likely due to the same changes whether this be a Skellett issue or a base Skript issue, as shown if you run this Skript with Skript2.5alpha5 and Skellett 1.9.8 and then update Skellett, where it breaks:

> command /test:
>   trigger:
>     loop enchantments of player's tool:
>       remove 1 from level of loop-enchantment of player's tool

As it's working with Skript 2.5alpha5 and Skellett 1.9.8 but broken if I update just Skellett to 1.9.9 with no other changes I assume it's a Skellett-end issue?

**Comment by TheLimeGlass** [comment]
I don't think Skellett has had any ClassInfo for enchantments. Must have been something with Skript changing.

The Skellett syntax is `enchant[ment] level (from|of) %enchantment% (of|in|on) %itemstack%`
