### ISSUE TITLE
on pick up: (interference)

### ISSUE THREAD

**Issue by JerryTheSlime16** [TheLimeGlass/Skellett#102]
Whenever I have Skellet installed & try to use this event it doesn't work properly.  I am not sure if this is something I can fix or if it has to be changed in Skellet; below I have some code of where I am using this (what it is not working for).

```vb
on pick up:
	if item's name is "ukulele":
		cancel event
		hasSH_Item(player, "ukulele") is false
		console command "/lp user %player% permission set ukulele.item"
		add "ukulele" to {sj::%uuid of player%::sh::*}
		message "{@prefix} &aCongratulations! You have collected the &2&oUkulele!!" to player
```

**Comment by TheLimeGlass** [comment]
Skellett doesn't have the on pickup event, that's part of Skript.
