### ISSUE TITLE
Doesn't work in 1.9.4 version of paper-spigot

### ISSUE THREAD

**Issue by NyuWay** [TheLimeGlass/Skellett#109]
When I am puting the jar plugin file into the server's plugin folder, all skript addons and skript itself are broken.

It just loaded in console but it's doing nothing. May It's beacause of a compatibility problem with addons.

→ I tested it with the last newer skript version (2.5) with such a big list of addons:
» (TuSKe, thatpacketadon, skwaze, skutilities, skript-yaml, skript-reflect, skript-json, skrayfall, skquery, sk-perm, skore, skent, skemail, skdragon, skbee, sharpsk, fawesk, boringsk, expressionsplus, holographicdisplayaddon)

one of these are probably incompatible...

**Comment by TheLimeGlass** [comment]
Send console log.

Skellett does not break Skript.
