### ISSUE TITLE
Skellett Scoreboard Teams

### ISSUE THREAD

**Issue by NickDanvers** [TheLimeGlass/Skellett#117]
When I use the Prefix syntax in scoreboard teams it just removes the command, example:

`command /test:`
`    trigger:`
`        register scoreboard team "test"`
`        set scoreboard prefix of team "test" to "test"`

Now, If you do `/test`, it will send the unknown command message.

Also, when you use `add entry`, it will send an error saying `can't understand this condition/effect`.
Thank you for reading & have a good day.

**Comment by TheLimeGlass** [comment]
Send the full error message.

A command registered in Skript to then say unknown command message is nothing related to Skellett.

**Comment by NickDanvers** [comment]
Here's the error.
Also when I do /skript:<tab>, it doesn't show up on the tab completion list. So the command is not even registered when I use prefix.

![javaw_OWEa6y0ok3](https://user-images.githubusercontent.com/79445712/108813462-bc17ad80-75b9-11eb-9d5a-c845bb29a736.png)
