### ISSUE TITLE
Packets

### ISSUE THREAD

**Issue by Davyde500** [TheLimeGlass/Skellett#120]
Im Using Spigot 1.8.8 I Used This Code: 

on packet:
    if event-string is "PacketPlayInSettings":
        set {_this} to packet field "a"
        broadcast "Language: %{_this}%"
        set {_this} to packet field "b"
        broadcast "View distance: %{_this}%"
        set {_this} to packet field "c"
        broadcast "Chat setting: %{_this}%"
        set {_this} to packet field "f"
        broadcast "Lefty or Righty: %{_this}%"
        
when i reloaded the skript is said "Can't understand this event On Packet"

**Comment by TheLimeGlass** [comment]
There are no packets in Skellett
