### ISSUE TITLE
Skellett help

### ISSUE THREAD

**Issue by PLASTAR-2748** [TheLimeGlass/Skellett#124]
Hello I would like to ask I downloaded the skellett plugin but I still don't want to take the format
set {prefix.hraca} to placeholder "cmi_user_prefix"
I need advice
version 1.17

**Comment by TheLimeGlass** [comment]
In the config.yml or syntax.yml there should be a node to disable it

**Comment by TheLimeGlass** [comment]
Just use skript-placeholder.
