### ISSUE TITLE
When a user connects to the server, a message is displayed in the console.

### ISSUE THREAD

**Issue by geumu** [TheLimeGlass/Skellett#125]
**Describe the bug**
When a user connects to the server, a message is displayed in the console.

**To Reproduce**
When I connect to the server, a message is generated in the console.
Video: https://youtu.be/ulXRFUWbSv0

**Information**:

Skript version: v2.2-dev37c
Server software: Catserver
Server version: 1.12.2
Additional context
Log: https://pastebin.com/B2FKae2b

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.0
