### ISSUE TITLE
Block hardness not working on 1.16.5?

### ISSUE THREAD

**Issue by zyxlonkka** [TheLimeGlass/Skellett#127]
This is not working:
[the] block (break delay|durability|hardness) of [all] %block%

Even tried this out with your example skript.
`command /hardness [<number>]:
    trigger:
        broadcast "%block hardness of target block%"
        if arg 1 is set:
            set block hardness of target block to arg 1
            broadcast "&cNew: %block hardness of target block%`

**Comment by TheLimeGlass** [comment]
Removed in 2.0.0, it's in Skript now.
