### ISSUE TITLE
Books won't work in Paper 1.16.5

### ISSUE THREAD

**Issue by yeuxdisent** [TheLimeGlass/Skellett#129]
13.09 07:14:02 [Server]  java.lang.IllegalAccessException: class EffAddComponentToPage cannot access a member of class org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaBook with modifiers "protected"
13.09 07:14:02 [Server]  at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
13.09 07:14:02 [Server]  at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
13.09 07:14:02 [Server]  at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075)
13.09 07:14:02 [Server]  at java.base/java.lang.reflect.Field.get(Field.java:416)
13.09 07:14:02 [Server]  at EffAddComponentToPage.execute(EffAddComponentToPage.java:45)
13.09 07:14:02 [Server]  at ch.njol.skript.lang.Effect.run(Effect.java:51)
13.09 07:14:02 [Server]  at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
13.09 07:14:02 [Server]  at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
13.09 07:14:02 [Server]  at ch.njol.skript.effects.Delay$1.run(Delay.java:108)
13.09 07:14:02 [Server]  at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
13.09 07:14:02 [Server]  at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
13.09 07:14:02 [Server]  at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427)
13.09 07:14:02 [Server]  at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
13.09 07:14:02 [Server]  at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
13.09 07:14:02 [Server]  at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
13.09 07:14:02 [Server]  at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
13.09 07:14:02 [Server]  at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.0
