### ISSUE TITLE
"send centered" Effect Doesn't Work With Color Codes

### ISSUE THREAD

**Issue by UsainSrht** [TheLimeGlass/Skellett#135]
![Screenshot_2](https://user-images.githubusercontent.com/59025999/137080706-30f1a586-8491-4590-8d33-c8c8240370dc.png)
Screenshot is describing everything :) 
Very helpful effect hope gets fix soon.

**Comment by TheLimeGlass** [comment]
Centered message has been removed because the client aka players can now change their chat length and that makes this syntax invalid.

You can just add spaces to your messages now.
