### ISSUE TITLE
 Skellett v2.0.0 - Startup error

### ISSUE THREAD

**Issue by MennoGamed** [TheLimeGlass/Skellett#139]
Hello,
As soon as I start my server I get this error when Skellet tries to load.

Pastepin link: https://pastebin.com/zuxDA5GB

Software:
- Minecraft version: 1.17.1
- Server.jar: git-Airplane-55 (MC: 1.17.1) ([Click for a link to the server.jar](https://ci.tivy.ca/view/Purpur/))

**Comment by ybadfg78** [comment]
me too

**Comment by TheLimeGlass** [comment]
It's due to the usage of SkBee, I made a pull request on SkBee here https://github.com/ShaneBeee/SkBee/pull/117

**Comment by TheLimeGlass** [comment]
Moved Item Frame syntaxes to Khoryl, so this error is now present in Khoryl, or it overrides SkBee, I haven't tested. Waiting on Pull Request.
