### ISSUE TITLE
Clarify the workflow to Skellett

### ISSUE THREAD

**Issue by jewome62** [TheLimeGlass/Skellett#14]
I have some questions about the workflow of this Repository.
Let me explain.

The update is confidential, not page on spigot/bukkit dev and not release on github for have notification of update.
The commit disappears, when have 2 commit but last month, it was 10 ? is not logic.
On the skunity forum, the link pointing here for the beta, but the beta is older than a release upload to skunity.
No real documentation.

I'm not here to criticize, but to try to showcase this addon and improve it. It's very useful plugin.
But for understand some thing, I may contact you on many channel, but i don't now is you know the problem or if i'm the first

I have work a little on a minecraft plugin. ( https://github.com/NLthijs48/AreaShop ) I dont have any help of maintener to create a pull request to improve the project. Because the workflow is clear.
On every push on github, jenkins create a build and this is dev build, for try.

When he has when has enough functionnality, and it's stable. It create a release on github. And update the spigot page for notify all the old downloader  (i update all my plugin with it)

Do you want help to improve this ?

And I think (but it's only mine opinion) the support doesn't be on skunity forum. Because, we have a thread with 1200 messages. Impossible to search and capitalize on the answer to improve the project. It's good for help the newbies but not for pull up bugfixes.

I remain available to speak and debate this.

Thanks

**Comment by TheLimeGlass** [comment]
I use egit to update and commit changes to this Skellett github, but for some reason the main plugin doesn't want to commit and cancels everytime. I have to create a new project setup everytime I want to send a commit. It's very annoying to do which is why I don't do it often. Also I'm using Git as a benchmarker right now. Anything that hasn't been commited means it needs to be recoded. I recently went through a huge recode from version 1.6.9 to 1.7 everything got changed.

I will release it soon once I finish recoding everything.

Then from there once it's on github, I would love any contribution to it. Thanks

**Comment by jewome62** [comment]
I'm PHP developper, and i use PHPStorm for code (I think is the better for PHP)
But often, the editor aren't good for git management, I use always SmartGit for commit/manage my Git repository.

I would see your code (even if is a recode) because actually this is the only source to know how work addons. And the user can contribute to help you with some bugfix, documentation and if they understand, they can explain to other (and you have less support)

Other thing, a good practice, If you code is not compatible (i don't know if it the case, because i don't know the change log between 1.6.7 and 1.7) you may change the first digit of your version (1.6.9 => 2.0.0) http://semver.org/ You have some article on internet more understandable for this but i take you the reference.

It will be a pleasure to help you
