### ISSUE TITLE
Add book support for Skript 2.5.3

### ISSUE THREAD

**Issue by GttMone** [TheLimeGlass/Skellett#140]
Hello,
Could you fix the books in your previous Skellett version (1.9.11), because it works with TuSKe, which works with skript 2.5.3, which only works on 1.16.5 version. Skript 2.6 breaks TuSKe and that's the best GUI system so far. I've tried skript-gui but it's not yet enough supportedand some of the features don't work.

I would be happy if you fix it in the previous version because I really need it.
If you would like I can send a payment if it's too difficult to do for free. 
Thanks in advance,
GttMone

**Comment by TheLimeGlass** [comment]
Explain what's not working about the book syntaxes? Books are in vanilla Skript. The only syntax Skellett has is opening of a book, but that's soon to be in Skript too.

**Comment by GttMone** [comment]
I have the same issue just like here: https://github.com/TheLimeGlass/Skellett/issues/103
You've commented that the books are fixed in version 2.0.0. I want to use the previous version 1.9.11. Is it possible to fix it in that version?

**Comment by TheLimeGlass** [comment]
You can use the latest versions of everything and try this patcher tool on Tuske https://github.com/TPGamesNL/SkriptAddonPatcher
