### ISSUE TITLE
Were the SQL functions removed?

### ISSUE THREAD

**Issue by GatoVuelta** [TheLimeGlass/Skellett#142]
Hello, So I'm trying to use the following in a skript

```
set {_resultat} to mysql result of query "SELECT * FROM xxxxx WHERE 'xxxxx' = '%xxx%'"
```

I enabled the settings in the skellet config file and all, but skript tells me that "Can't understand this condition/effect"

**Comment by TheLimeGlass** [comment]
Ya they were removed

**Comment by GatoVuelta** [comment]
Can I have an old version of Skellet that still works with SQL? or something bad will happen?

**Comment by TheLimeGlass** [comment]
Look on the Spigot page, and click version history. You should be using skript-db for MySQL, or just Skript with the config.sk configurations
