### ISSUE TITLE
Citizen Invulnerability / Vulnerability syntax breaks citizen.

### ISSUE THREAD

**Issue by AlexWarriorPlays** [TheLimeGlass/Skellett#144]
I'm just messing around with the different citizen related syntaxes and I found if you make a citizen Vulnerable then it completely breaks them. They cant move, attack, or do any actions. It also just does not work as they cannot be punched.

Skript version: 2.5.3
Jar: Nachospigot 1.8.8 - b6bc177
skellett version: 2.0.1

**Comment by TheLimeGlass** [comment]
Duplicate and fixed in 2.0.4 https://github.com/TheLimeGlass/Skellett/issues/167
