### ISSUE TITLE
New Time Expression

### ISSUE THREAD

**Issue by Norbiros** [TheLimeGlass/Skellett#156]
I cant do something like this:
`set {_time} to milliseconds of {_timespan}`
I need to use
`set {_time::*} to milliseconds of {_timespan}`
Why i need to use list when list has only 1 element?

It has very easy fix, change this to "true":
`@Override
	public boolean isSingle() {
		return false;
	}`

I'm not creating PR, because i don't know if it is intentional..

**Comment by TheLimeGlass** [comment]
Ya that's a bug. Fixed in next version and you can download it at https://github.com/TheLimeGlass/Skellett/suites/5139035606/artifacts/154900978
