### ISSUE TITLE
Unsupported version - 1.9.4

### ISSUE THREAD

**Issue by MrDrake52000** [TheLimeGlass/Skellett#16]
Hello :)
I'ven encountered an issue with Skellett, all is in the title. I'm running Spigot version 1.9.4.R0.1-SNAPSHOT
(CraftBukkit version git-Spigot-798f32d-0cd0397)
I give you a screenshot of the error : http://puu.sh/tmyMt/ca1cf8e8bb.png

Is it something with the plugin or my version of Spigot ? If it's the plugin, can you try to update it for 1.9.4 version ? Thanks a lot !

**Comment by TheLimeGlass** [comment]
The issue is you need Java 8 to run Skellett. Also plugman conflicts with alot of Skript addons and it's highly recommened to not use it.
