### ISSUE TITLE
Breaks all skripts when I add it

### ISSUE THREAD

**Issue by Henry-Bonikowsky** [TheLimeGlass/Skellett#164]
The second I put Skellet jar file into my plugins folder and start up, instant severe errors for all my skript files. I'm running 1.18.2 with 2.6.1 Skript, and latest version of Skellet, but Skellet is so F*cked up right now I don't know what to do. I need it for many things.

**Comment by RollexGrief** [comment]
same

**Comment by MadPanCake** [comment]
Yeah, same case for me. I have installed the newest version on my 1.18.2 server, with newest Skript and it's broken. Makes all my scripts throw huge errors and makes them don't work.

**Comment by lastedito** [comment]
same

**Comment by TheLimeGlass** [comment]
Duplicate and fixed in 2.0.4 https://github.com/TheLimeGlass/Skellett/issues/167
