### ISSUE TITLE
Classes not on github

### ISSUE THREAD

**Issue by drtshock** [TheLimeGlass/Skellett#17]
Hello,

I'm attempting to compile Skellet without the file editing abilities (create, edit, list, etc.) but when I download the jar from Spigot, there are a ton more classes than what's on Github here. I'm hoping I just made a silly mistake, or that you can help me out by pushing everything that isn't on Github if that's the case :)

<img width="213" alt="screen shot 2018-09-18 at 13 30 36" src="https://user-images.githubusercontent.com/2638275/45714648-1689c580-bb47-11e8-89a2-f5a1ee114bff.png">
<img width="185" alt="screen shot 2018-09-18 at 13 30 25" src="https://user-images.githubusercontent.com/2638275/45714649-1689c580-bb47-11e8-81ea-f1c7703e49b5.png">

**Comment by TheLimeGlass** [comment]
https://github.com/TheLimeGlass/Skellett-Legacy

**Comment by drtshock** [comment]
What...? So you want me to use an archived repo?

**Comment by TheLimeGlass** [comment]
If you haven't noticed this repo is a re-write of the software.

**Comment by drtshock** [comment]
So what are you releasing and why is the release branch archived? Doesn't make sense to me. Is the source on the legacy branch the same as the most recent version of https://www.spigotmc.org/resources/skript-java-addon-skellett.34361/ ?

**Comment by drtshock** [comment]
Would love an answer on this, my users want it badly but I'm not going to use an archived repo.

**Comment by TheLimeGlass** [comment]
Why it's the same.

**Comment by drtshock** [comment]
https://github.com/Minehut/Skellett

I made my own fork, sorry for removing git history. Please learn how to use dependency management as well as keeping your source up to date if you plan on making open source software that you want people to not hate you for.
