### ISSUE TITLE
Long Error (Happens when SkBee is added)

### ISSUE THREAD

**Issue by ImNotStable** [TheLimeGlass/Skellett#173]
Server Version: git-Paper-386 (MC: 1.18.2)
Skript Version: 2.6.2
Installed Skript Addons:
- Skellett v2.0.5 (https://forums.skunity.com/resources/skellett.24/)
- SkBee v1.16.1 (https://github.com/ShaneBeee/SkBee)
Installed dependencies:
 - Vault v1.7.3-b131

Plugins (5): LuckPerms, SkBee, Skellett, Skript, Vault

Error: https://pastehub.net/b159fc0f0c4
Script: https://pastehub.net/b15a2677a82

All configs are unchanged

**Comment by TinyMandalorian** [comment]
I have this same issue with very long error with skbee as well!

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.6
