### ISSUE TITLE
bossbar doesn't work

### ISSUE THREAD

**Issue by RunqRun** [TheLimeGlass/Skellett#174]
I tried this code, but it doesn't work
**add the bossbar {_test} to player**

Error:
**Can't understand this condition/effect: add the bossbar {_test} to player**

**Comment by RunqRun** [comment]
Addon:
**SkBee
Skellett
SkQuery**

**Comment by ImNotStable** [comment]
To post the info needed to test the bug use /sk info and post what's there, also what is the entire script because {_test} can't be an empty variable
Also, in #173 it's been shown Skellet and SkBee conflict with their scoreboards or teams

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.6
