### ISSUE TITLE
[bug]nametag cannot change player id color

### ISSUE THREAD

**Issue by lizheyo77** [TheLimeGlass/Skellett#188]
on join:
    create nametag "tag"
    Set {_tag} to placeholder "tcs_ch" from player
    set prefix of nametag "tag" to "&r&f%{_tag}% &a"
    add player to nametag "tag"
On Quit:
    remove player from nametag "tag"

this

**Comment by TheLimeGlass** [comment]
You need the nametag plugin that's the name
