### ISSUE TITLE
It causes all players to have the same nameplate, or random

### ISSUE THREAD

**Issue by lizheyo77** [TheLimeGlass/Skellett#189]
on join:
    create nametag "tag"
    Set {_p} to placeholder "player_name" from player
    Set {_tag} to placeholder "tcs_ch" from player
    set {tag::%player%} to {_tag}
    set prefix of nametag "tag" to "&r&f%{tag::%player%}% "
    if player has permission "tcsch.mrch":
        add player to nametag "tag"

**Comment by TheLimeGlass** [comment]
You need the nametags plugin that's the name
