### ISSUE TITLE
disconnect to mysql

### ISSUE THREAD

**Issue by TheMeq** [TheLimeGlass/Skellett#19]
[13:45:39 ERROR]: Can't understand this condition/effect: disconnect to mysql (TerraRune.sk, line 13: disconnect to mysql')

**Comment by JamesBAM** [comment]
I think the syntax you are looking for is:

`disconnect from mysql`

**Comment by TheMeq** [comment]
Fixed, documentation was wrong on SkUnity.

**Comment by TheLimeGlass** [comment]
This was fixed on the docs. Thanks for that report
