### ISSUE TITLE
Skelett doesn't work with purpur

### ISSUE THREAD

**Issue by LutrexMC** [TheLimeGlass/Skellett#192]
Somehow the skelett skript addon doesn't work with purpur, it works with paper, is it possible that they can fix this, or do I have to contact the purple developers?

LG

**Comment by TheLimeGlass** [comment]
probably not related to purpur use 2.0.8

**Comment by LutrexMC** [comment]
Where can I find the version?

**Comment by LutrexMC** [comment]
> probably not related to purpur use 2.0.8

Unfortunately it still doesn't seem to work :(
