### ISSUE TITLE
java.lang.IllegalArgumentException: Can't register net.md_5.bungee.api.chat.TextComponent with the code name textcomponent because that name is already used by text component

### ISSUE THREAD

**Issue by garbi23** [TheLimeGlass/Skellett#195]
java.lang.IllegalArgumentException: Can't register net.md_5.bungee.api.chat.TextComponent with the code name textcomponent because that name is already used by text component 

An error occurred every time I added a plugin.  There is no TextComponent in the added plug-in.

**Comment by ghost** [comment]
This looks similar  to issue #193.
If you use "SkBee" then try disabling text component in SkBee's config file.

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.9
