### ISSUE TITLE
Ground State expression error

### ISSUE THREAD

**Issue by sandor111** [TheLimeGlass/Skellett#22]
Hey i was using this code:
on shoot:
    while ground state of shot projectile is false:
        push shot projectile upwards at speed 0.15
        wait 1 second
When i got this error:
http://pastebin.com/43kwnfvi

**Comment by TheLimeGlass** [comment]
Use shot arrow.

This bug is fixed in the next update. Thanks for the bug report 👍

**Comment by sandor111** [comment]
When is the new update :p

**Comment by TheLimeGlass** [comment]
https://forums.skunity.com/threads/skellett-the-addon-with-a-beast-name.39/
