### ISSUE TITLE
Misleading Description (0/10 ⭐️)

### ISSUE THREAD

**Issue by ghermm** [TheLimeGlass/Skellett#224]
Now now now Mr. Limeglass 🤓 I know what you're gonna say "but it is the most popular, gherm!" Well mister fister, maybe it was at one point, but not anymore, silly willy. Now, it's SkBee. So I recommend changing the, uh, description. And I know what you're gonna do, you're gonna make it say "_objectively_ the best addon." But, you silly goose, you see, it's not the best and you know that big babe. So, please change the description to "Skript addon" and I'll leave you to it, you fiery keister.

See ya later, alligator! (You say: "afterwhile, crocodile!") 🤭

Thank you!

**Comment by TheLimeGlass** [comment]
Who are you? https://www.spigotmc.org/resources/categories/skript.25/?order=download_count

**Comment by ghermm** [comment]
🫣 Budsy boo, I am gherm, as the GitHub name implies. And, by the looks of bStats itself (I know, I'm such a nerdsy werdsy), SkBee is a bigger and badder addon than little ole Skellet here. I'll give you a couple of picsy wicsies to ponder over my dearest. Now, make sure to tell me "afterwhile crocodile!" 🐊 ROAR!!! 🙂‍↕️ 
![image](https://github.com/TheLimeGlass/Skellett/assets/143357165/65169229-2e4b-4de0-bcba-5085f7ea3a61)
![image](https://github.com/TheLimeGlass/Skellett/assets/143357165/9aac92c3-ba82-4476-adfd-535f04e2c0ea)

**Comment by ghost** [comment]
> Who are you? https://www.spigotmc.org/resources/categories/skript.25/?order=download_count

but its skquery....
