### ISSUE TITLE
Possible expression conflict between Inventory's type and Entity's type

### ISSUE THREAD

**Issue by GaelErhlich** [TheLimeGlass/Skellett#23]
Hi, I noticed that if I use this expression from Skript in 1.11.2:
`loop-entity's type`
...it creates a conflict with this expression from Skellett:
`inventory's type`
...and there is an error : 

> [17:20:16 ERROR]: #!#!
> [17:20:16 ERROR]: #!#! [Skript] Severe Error:
> 
> [...]
> 
> [17:20:16 ERROR]: #!#! Stack trace:
> [17:20:16 ERROR]: #!#! java.lang.NullPointerException
> [17:20:16 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprInventoryType.get(ExprInventoryType.java:45)
> [17:20:16 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprInventoryType.get(ExprInventoryType.java:1)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:488)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:69)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
> [17:20:16 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
> [17:20:16 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [17:20:16 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [17:20:16 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [17:20:16 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
> [17:20:16 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
> [17:20:16 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [17:20:16 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
> [17:20:16 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1336)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
> [17:20:16 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> [17:20:16 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
> [17:20:16 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
> [17:20:16 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
> [17:20:16 ERROR]: #!#!
> [17:20:16 ERROR]: #!#! Version Information:
> [17:20:16 ERROR]: #!#!   Skript: 2.2-dev23
> [17:20:16 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
> [17:20:16 ERROR]: #!#!   Minecraft: 1.11.2
> [17:20:16 ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
> [17:20:16 ERROR]: #!#!   OS: Windows 10 amd64 10.0
> [17:20:16 ERROR]: #!#!
> [17:20:16 ERROR]: #!#! Running CraftBukkit: false
> [17:20:16 ERROR]: #!#!
> [17:20:16 ERROR]: #!#! Current node: null
> [17:20:16 ERROR]: #!#! Current item: broadcast "%Inventory type%"
> [17:20:16 ERROR]: #!#!
> [17:20:16 ERROR]: #!#! Thread: Server thread
> [17:20:16 ERROR]: #!#!
> [17:20:16 ERROR]: #!#! End of Error.
> [17:20:16 ERROR]: #!#!`

You can prevent this issue by using:
`type of entity`
But if you don't know that the other expression may cause conflicts and you don't use Skellett, it may create problems with other people using your Skript plugin.

**Comment by TheLimeGlass** [comment]
This is fixed in the next update.

Thanks for the bug report.
