### ISSUE TITLE
"Entities in radius around location" expression not working

### ISSUE THREAD

**Issue by sandor111** [TheLimeGlass/Skellett#24]
When i use this skript:
set {_l} to location of targeted block
				distance between player and {_l} is less than 50:
					broadcast "tes232t"
					loop all entities in radius 10 around {_l}:
						broadcast "test"
						push loop-entity upwards at speed 3
I get this error:
http://pastebin.com/LKFwsLXP

**Comment by TheLimeGlass** [comment]
What Version is your 1.8 server?

**Comment by TheLimeGlass** [comment]
Could not replicate issue

**Comment by sandor111** [comment]
1.8.0 is my minecraft version and skript is https://github.com/bensku/Skript/releases/tag/dev23

**Comment by TheLimeGlass** [comment]
Try updating to 1.8.8

Or if you would like to help me. Update one by one each version like 1.8.1 then 1.8.2 then 1.8.3 then 1.8.4 etc until the error stops working.

If you don't check each version like that. I will check to see which version added this method and make a fix.

**Comment by sandor111** [comment]
?

**Comment by TheLimeGlass** [comment]
This doesn't work in some versions lower than 1.8.2

**Comment by TheLimeGlass** [comment]
This is in vanilla Skript now.
