### ISSUE TITLE
Feature Request: HTTP Post Request

### ISSUE THREAD

**Issue by mrpetfreak** [TheLimeGlass/Skellett#26]
I'm suggesting a possibility to make a http post request to a website from skript.
Syntax could be an expression like

`post request with key %text% and value %text% and key %text% and value %text% to %text%`

The last %text% is the website url.
The assigned variable returns successful (true) or false.
This expression is helpful when pushing data to a website api.

**Comment by Snow-Pyon** [comment]
this is already possible with [Reqn](https://github.com/btk5h/reqn).
