### ISSUE TITLE
Player not connect spigot 1.14.2

### ISSUE THREAD

**Issue by aviations** [TheLimeGlass/Skellett#27]
- git-Spigot-df0eb25-da071ec (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
- Skript-2.4-alpha3
- Tested with Skellett 1.9.6b 1050KB and 1039KB

result : when a player as connected : Disconenct with this consol error (lost connection: Internal Exception: java.lang.IllegalStateException: EvtPacket cannot be triggered asynchronously from another thread.)

**Comment by TheLimeGlass** [comment]
Disable packets in the syntaxtoggles.yml

**Comment by aviations** [comment]
Its good, thanks you
