### ISSUE TITLE
Version of player

### ISSUE THREAD

**Issue by RikoDEV** [TheLimeGlass/Skellett#27]
**I use example:**
```
on join:
    if minecraft version of player is "1.9":
        send "You're joining with version %mc version of player%!"
```

**on latest Skellett, bensku Skript and Spigot.
When I run the script receives error:**

`Can't compare 'minecraft version of player' with a text (skrypt.sk, line 13: if minecraft version of player is "1.9")`

Please fix it.

**Comment by TheLimeGlass** [comment]
This isn't a thing in Skellett. It's from RandomSk, but I will look into adding it.

**Comment by TheLimeGlass** [comment]
You can use ProtocolSupport and Skellett to determine the protocol of the player
http://skunity.com/search?search=ProtocolSupport+-+Protocol+version#
