### ISSUE TITLE
Pitches for sounds

### ISSUE THREAD

**Issue by Remixful** [TheLimeGlass/Skellett#32]
https://github.com/TheLimeGlass/Skellett/blob/205269e07d08bde4fcdb4e13750c0188fff0caeb/SkellettGit/src/com/gmail/thelimeglass/Effects/EffPlaySound.java

I am pretty confused at why you made it like this.
For example, if I wanted to play a note of a noteblock, the note G for the octave 1 is 0.53.

How would I play the sound with the pitch 0.53? Why can't I just put with pitch 0.53 for the expression?
Can't you just math.clamp the pitch in between 0.5 and 2.0 and it's much easier to control the pitch now?

**Comment by TheLimeGlass** [comment]
Sound is now in vanilla Skript.
