### ISSUE TITLE
play sounds at a location give errors

### ISSUE THREAD

**Issue by Thijsje** [TheLimeGlass/Skellett#33]
These two don't work

play sound "BLOCK_GRASS_BREAK" at location of loop-value-2 with volume 2 and pitch 2

set {_pos} to location of loop-value-2
Play "BLOCK_CHEST_CLOSE" at {_pos} with volume 2 and pitch 1

**Comment by TheLimeGlass** [comment]
You need to make sure that the sound for your version of Minecraft exsists.

If you have a 1.8 server, these are your sounds https://github.com/Attano/Spigot-1.8/blob/master/org/bukkit/Sound.java

If you have 1.9+ these are your sounds https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
