### ISSUE TITLE
title message takes ages to reload

### ISSUE THREAD

**Issue by melinstagibson** [TheLimeGlass/Skellett#38]
Skellett 1.9.2, Skript Dev-28c, paperspigot 1.12-pre6

on 1.12 a script with the Effect

`show title "&6Title" and subtitle "&aSubtitle" to player for 5 seconds and 10 ticks fade in and 15 ticks fadeout`

takes an extra 5-10 seconds to load for each time you call it.
Not a big deal but kinda annoying

**Comment by melinstagibson** [comment]
That also freezes the server to a point where everyone gets kicked if i use more than 4 of those effects :/

**Comment by TheLimeGlass** [comment]
Ya I know about this. The syntax is big and the Skript parser is slow and parsing long syntax. Bensku found a slight issue with it and will fix the speeds in the next update. No clue how fast it will improve it though.

I can eliminate the Umbaska title syntax in the Skellett title as no one uses it anyways.
