### ISSUE TITLE
[on npc click] not working

### ISSUE THREAD

**Issue by MinecraftAdmin** [TheLimeGlass/Skellett#42]
Skellett 1.9.4a
Skript 2.2-dev29
Citizens 2.0.21-b1474
PaperSpigot 1.11.2

Using `on npc click` results in an error.
`can't understand this event 'on npc click'`

**Comment by TheLimeGlass** [comment]
This is a Citizens issue. It doesn't register the event for your spigot version. Use this as a workaround
```
on rightclick on entity:
    if clicked entity is a citizen:
        set {_npc} to npc from entity clicked entity
        if id of npc {_npc} is 69:
            #do stuff
```
