### ISSUE TITLE
Second line not formatted with Bungee Message event

### ISSUE THREAD

**Issue by Wasabules** [TheLimeGlass/Skellett#45]
Hi!

This event is buggy:

message coloured "TEXT" to bungeecord player "%loop-value%"

If your text is too long and make a second line, the second line is not formated (white text)

Example: http://prntscr.com/fpv0nh

Thanks :)

**Comment by TheLimeGlass** [comment]
This is an issue with Bungeecord you will have to manually send two messages or use %nl% expression from SkQuery and recolour the next line.
