### ISSUE TITLE
Bossbar issue with Skrayfall

### ISSUE THREAD

**Issue by kingdcreations** [TheLimeGlass/Skellett#47]
Skript 2.2Dev 29
Skelett 1.9.5
Got this error when using this skript: 
`command /kd:
    trigger:
        set {_bar} to new bossbar
        add player to bossbar {_bar}
        set the visibility of bossbar {_bar} to true
        hide bossbar {_bar}
        wait 2 seconds
        show bossbar {_bar}`

An internal error occurred while attempting to perform this command.

https://pastebin.com/KVbXnHUj

**Comment by TheLimeGlass** [comment]
Disable Skellett bossbar's or uninstall SkRayFall
