### ISSUE TITLE
Suggestion - UUID of entity.

### ISSUE THREAD

**Issue by Sollembum78** [TheLimeGlass/Skellett#48]
I know there is some uuid of entity which is used to define mobs like zombie, villager etc. It's also can be somehow accessed via vanilla scoreboard mechanics.

And there was one expression in umbaska that should give it, but since umbaska is not really active, would be nice to have this expression in skellett. 

Example use - we are using one plugin that allow player to summon his saved horse from another location. But it kills original horse and spawns copy of it elsewhere, and if WG region has spawn deny flag, horse is not spawned. But by teleporting mob by uuid we could just teleport exact mob to new location, without spawning.

**Comment by TheLimeGlass** [comment]
Already in Skellett xD
```
entity (uuid|[universal] unique id) of [entity] %entity%
#or
[entity] %entity%'s entity (uuid|[universal] unique id)
```
