### ISSUE TITLE
Client side borders not working?

### ISSUE THREAD

**Issue by Efnilite** [TheLimeGlass/Skellett#5]
When I let a player execute a command, there client side border should be set to 10. But that doesn't happen. If I add 'broadcast "%client border size of player%"' it comes up with <none> and followed by this error: https://pastebin.com/AWqNSEPm

The text I used for the border:
set client border size of player to 10

When I set the center of the border to the location of the player, I get this error:
https://pastebin.com/KyjJvtvK

**Comment by TheLimeGlass** [comment]
They only work for versions under 1.12.2
