### ISSUE TITLE
ProtocolSupport.

### ISSUE THREAD

**Issue by BrettplayMC** [TheLimeGlass/Skellett#58]
When running 1.9.4a (the only version that works for me), when I enable ProtocolSupport in the config, I get this on load: https://hastebin.com/sexubaneva.bash

**Comment by BrettplayMC** [comment]
.

**Comment by BrettplayMC** [comment]
.

**Comment by PanKlipcio** [comment]
I have the same error
https://hastebin.com/gusirutuji.css

**Comment by PanKlipcio** [comment]
In plugin.yml `, Protocol Support` was not added to _softdepend_
Maybe this is the source of the problem?

**Comment by TheLimeGlass** [comment]
The issue is that ProtocolSupport deprecated and I guess removed the materialData for new ProtocolSupport versions. When Skellett hooks gets updated I will look into updating this.
