### ISSUE TITLE
NPC Expressions

### ISSUE THREAD

**Issue by AceOfMinecrafts** [TheLimeGlass/Skellett#60]
I can't use an NPC as an expression or to a variable.
'set {npc} to npc' doesn't recognize 'Npc' as an expression, and there is no work around for this.

I therefor think NPC should be an expression, in order to properly use an NPC's attributes in a condition.
Such as checking if the npc's display name is equal to <Insert name>.

And 'on npc rightclick', cannot recognize it as a click event. For 'clicked-entity' returns an error. 
(This was an attempt at a workaround. To set the NPC to a variable, to then use in a condition.)

**Comment by LapizSeller** [comment]
Confirm this issues.
I'm try with this skript but it don't work
```
on npc click:
    broadcast "Hello npc"
```
and, how to make this skript work?
```
on npc right click:
    if npc is named "Merchant":
        make player execute command "/merchant"
```
server: 1.11.2
skellet 1.9.5
skript bensku dev 22f

**Comment by TheLimeGlass** [comment]
It's event-citizen

**Comment by LapizSeller** [comment]
@TheLimeGlass 
i'm try everything
npc, citizen, event-npc, event-citizen.
still won't work
