### ISSUE TITLE
SkellettProxy/Skellett Severe error + crash after Quitting and joining back

### ISSUE THREAD

**Issue by Adrihun** [TheLimeGlass/Skellett#61]
My problem:
When I join my server, and switch between servers. Like go from Hub to Factions with **send player to** skellettproxy and then Quit the whole server, and try to join back it won't work it will say Timed Out, and then it will crash the Hub server

I have a bungee server (1 hub, 1 creative server, 1 faction server)

Spigot 1.8.9
Bungee Latest
**I have these plugins:**
Skript 2.2 dev 25
Skellett 1.8.9
SkellettProxy 1.3.0b

When I join after quitting the server:
"Logging In" ... after 30 sec.... "Timed out"

Hub Crash -> (After getting kicked for Timed out)
_https://hastebin.com/iqiqetujeh.md_

When Quitting the whole server and i switched servers in bungee before (like went from hub to factions) (bungee error)
_https://hastebin.com/rehifowetu.css_

_I tried many things...._
**SkellettProxy**
- Disabling check for updates
- Disabling Network Variables
- Disabling Global Scripts
- Disabling Tracking
- Changing Allowed Trys to 10

**Skellett**
- Also tried Skellett 1.9.0e

**Comment by TheLimeGlass** [comment]
Please use Skungee as that is the newer more updated Bungeecord addon of SkellettProxy https://www.spigotmc.org/resources/skript-java-addon-skungee-bungeecord-addon-for-skript.35636/
