### ISSUE TITLE
Servers fail to communicate properly

### ISSUE THREAD

**Issue by mikroskeem** [TheLimeGlass/Skellett#63]
BungeeCord log: https://paste.wut.ee/ayupoyanex.sql  
Server log: https://paste.wut.ee/imosiqowuv.md  

Server just spams logs with EOFException.  
Is this caused by a misconfiguration or does it look more like plugin bug?

**Comment by TheLimeGlass** [comment]
Use Skellett latest and 1.3.3a with events set to false.

**Comment by TheLimeGlass** [comment]
1.3.3a of SkellettProxy that is
