### ISSUE TITLE
Skellet server can't connect to SkelletProxy.

### ISSUE THREAD

**Issue by xGioChR** [TheLimeGlass/Skellett#64]
Hi,
I am trying to figure out what I am doing wrong with the config file.
I am using the latest version of Skellet (1.9.6b), SkelletProxy(1.3.3b), Skript (Bensku's fork, dev31c) and PaperSpigot ( build n.1244).
I does not matter if I put the right port on both config files (Paper and Bungeecord ones), Skellet returns this error: https://pastebin.com/7sg2NE8g .
I tried writing my public IP, 127.0.0.1, 0.0.0.0 and even leaving localhost: none of those solutions have worked.
I would be grateful if you could help me solving this issue.

In addition, I would like to make clear that I really need this addon, since it is the only one that seems to work correctly with Bungeecord.
Thank you for your attention.

**Comment by TheLimeGlass** [comment]
Please use Skungee as that is the newer more updated Bungeecord addon of SkellettProxy https://www.spigotmc.org/resources/skript-java-addon-skungee-bungeecord-addon-for-skript.35636/
