### ISSUE TITLE
Unacceptable Server Crash Everytime I Reload the Skript

### ISSUE THREAD

**Issue by Techno3600** [TheLimeGlass/Skellett#66]
Hello,

I want to start off my saying that I am a pretty reasonable guy and I am very understanding to developers and their making of plugins, but I'm quite mad at this plugin and will not be using this plugin, this plugin literally crashes EVERY SINGLE TIME I do "/skript reload all". It also makes the server take an extra five minutes to start up every time because it takes so long to load. This addon makes it impossible to actually use skript to its fullest.
Here's the error: https://pastebin.com/Kf5GLWjH
I suggest you look into this immediately and push a hotfix.

Thanks
Techno3600

**Comment by melinstagibson** [comment]
now that was funny

how about you hotfix your scripts first and look at the stacktrace.

**Comment by Techno3600** [comment]
There’s only like 4 errors in the Skript and those are unavoidable errors. It lags like crazy in restart or reload and almost always crashes.

**Comment by TheLimeGlass** [comment]
There is nothing related to Skellett in this bug report. You have some space/tab indentation issues, invalid areas for Functions and the update effect which is from SkQuery. The crash is most likely related to Skript and these errors when parsing.

**Comment by Techno3600** [comment]
Um... I don't think this is a SkQuery Error as I don't have that plugin installed on my server.

**Comment by Techno3600** [comment]
Oops, wrong thingie, sorry about that
