### ISSUE TITLE
Reload too long on the title and subtitles

### ISSUE THREAD

**Issue by weberlepecheur** [TheLimeGlass/Skellett#67]
Hello,

I found an effect that I could use in one of my skripts skUnity but it takes more than a minute to reload (1m04s) this one when I use this effect:

`show a title from "§9Bravo !" and subtitle "§2vous remporté un triplé ! §6{@argent.gagnant.triple}€ §2!" to player for 5 seconds and 7 ticks fade in and 15 ticks fadeout`

In the description of the doc it is noted this, but I do not fully understand what it means.

> Create a title with an optional subtitle send title and subtitle Note: If the syntax is laggy when reloading change the syntax in your config. Read the skellett config. It will tell you everything about the issue and how to fix. The best method is download Bensku's latest edit as he is working on a fast multi thread fix for this issue.

Spigot 1.12.2
Skript dev31b
Skellett 1.9.6b

**Comment by TheLimeGlass** [comment]
This is due to the reflection casting needed to execute the title effect on different versions and Skript itself when it comes to these things. I have planned to have a option to toggle reflection for Skellett 2.0
