### ISSUE TITLE
Skellet Errors on 1.8 A Lot

### ISSUE THREAD

**Issue by Techno3600** [TheLimeGlass/Skellett#71]
Hi,

These are the whole error responses from quite a different number of times. I am pretty sure that most of this stuff is Skellet error-ing on 1.8, though the Skript plugin could also be error-ing. [Here is the error](https://pastebin.com/gi1Njr7x).
(I am running spigot-1.8.0)

Thanks
Techno

**Comment by TheLimeGlass** [comment]
Try using Skript 2.2 and a different 1.8 version from the one you're using. Some versions don't have the channel netty field in them for some reason from Mojang. You can find 2.2 here https://github.com/bensku/Skript/releases

**Comment by TheLimeGlass** [comment]
1.9.7 has no packets anymore.
