### ISSUE TITLE
Nametag editing

### ISSUE THREAD

**Issue by GermanMinerDE** [TheLimeGlass/Skellett#79]
Hey!

The functions for name tag-editing do not work for us after updating to Spigot 1.12.2.

Spigot Build: 1.12.2
Skellett: 1.9.6b

Functions with errors:

- create tag with id
- set suffix tag with
- set prefix tag with
- add player to nametag
- and every other...

Thank you!

**Comment by TheLimeGlass** [comment]
What do you mean they don't work?
