### ISSUE TITLE
BungeeBridge bug

### ISSUE THREAD

**Issue by yyeerai** [TheLimeGlass/Skellett#8]
set {_MOTD} to MOTD of server "Hub"
    message "%{_MOTD}%"
    
Use the above code server crash

**Comment by itismejoey** [comment]
You should provide any server errors that you get.

**Comment by TheLimeGlass** [comment]
@yyeerai The issue is that you don't have a server named "Hub" it may be in lowercase "hub" but the main issue is that you don't have a server with that string.

Example script I used to test (Which worked fine)
```
on load:
	loop all bungeecord servers:
		set {_MOTD} to MOTD of server "%loop-value%"
		broadcast "%{_MOTD}%"
```
