### ISSUE TITLE
Teleporting between worlds

### ISSUE THREAD

**Issue by ghost** [TheLimeGlass/Skellett#83]
When I tried to teleport between worlds using "teleport player to world "test"" It sends a severe error in the console, I asked in skUnity and they said it was skellett related.
![dadada](https://user-images.githubusercontent.com/19301522/65651562-c86e9400-dfdc-11e9-9b5f-baded0548e6c.JPG)

**Comment by TheLimeGlass** [comment]
The world is probably null, user error. Either the world you want to teleport to doesn't exist or it was null. I can fix this from erroring, but it won't make the syntax work.

Make sure the worlds you are using in the syntax aren't null.

**Comment by TheLimeGlass** [comment]
Fixed in the next version.
