### ISSUE TITLE
Enchant detection is changed with Skellet.

### ISSUE THREAD

**Issue by aescraftbr** [TheLimeGlass/Skellett#86]
When using skellet, this code will only detect the type of the enchantments, not its level:

```
command /iten:
  trigger:
    send "enchantments of player's tool = &d%enchantments of player's tool%"
```

With skellet: https://i.imgur.com/jI3IN8g.png
Without skellet: https://i.imgur.com/L9kh6w0.png

So skellet is messing with "enchantments of player's tool" expressions.

**Comment by TheLimeGlass** [comment]
This is now in vanilla Skirpt.
