### ISSUE TITLE
Launch / Deploy not working for fireworks

### ISSUE THREAD

**Issue by Dinoosawruss** [TheLimeGlass/Skellett#88]
Hi,

I am trying to use launch / deploy for fireworks
I have tried both launch and deploy neither have worked

**CODE:**
```
command /fw:
	trigger:
		deploy "BURST" at location of player with timed 1
```

**ERROR:**
Can't understand this condition/effect: deploy "BURST" at location of player with timed 1 (newYears.sk, line 3: deploy "BURST" at location of player with timed 1')

**Comment by TheLimeGlass** [comment]
Fireworks are in vanilla Skript, check the syntax for fireworks at skripthub.net or use SkQuery for fireworks
