### ISSUE TITLE
Book creation on 1.14

### ISSUE THREAD

**Issue by Tomasekg15** [TheLimeGlass/Skellett#93]
Hello i have a problem with my Skellett where i want to make a book but it thows me an error at every sigle line. Can you help me?

my code:
command /testbook:
  trigger:
    set {_book} to new written book
    add a page with text "Hello" to book {_book}
    set author of book {_book} to "&aLime"
    set page 1 in book {_book} to "&6Hello testing"
    open book {_book} to player

(the spaces are correct, it just doesn't show up)

**Comment by TheLimeGlass** [comment]
The "new written book" syntax has been added back in 1.9.9
