### ISSUE TITLE
scoreboard error

### ISSUE THREAD

**Issue by arts7493** [TheLimeGlass/Skellett#94]
i'm using skellett stylish scoreboard
but i cant use color glow with eGlow plugin
https://www.spigotmc.org/resources/eglow-1-9-4-1-15-x-glow-cosmetic-respects-eula-mysql-new-citizens-support.63295/

**Comment by TheLimeGlass** [comment]
The team needs to be added to the colour, and then the glowing state of the entities needs to be set.
