### ISSUE TITLE
Expressions don't work on 1.15.2

### ISSUE THREAD

**Issue by HosonPig** [TheLimeGlass/Skellett#95]
Some expressions like " a new written book" is not working on 1.15.2

**Comment by Damien0503** [comment]
I agree, I tried to use this expression and it does not work. The expression is not recognize by Skript.

**Comment by WoojinSim** [comment]
I am also using Skript 2.4.1 version on Paper version git-Paper-1618 server and I having the same problem.

**Comment by TheLimeGlass** [comment]
It's been added back in 1.9.9
