### ISSUE TITLE
Syntax conflict or something like that

### ISSUE THREAD

**Issue by ghost** [TheLimeGlass/Skellett#98]
sometimes it errors out very many of my scripts that use "on break" event, with something related to Hanging, if I disable Hanging in syntax toggles, it stops

been having this problem for a while, but it was a long time since last I had it, so sorry I don't exactly have an error to show, but been happening on 1.12.2 and Skellett 1.9.8

**Comment by TheLimeGlass** [comment]
MundoSk has hanging syntax, are you running MundoSk?

**Comment by Govindass** [comment]
oh yes I am, then that could be the problem

**Comment by TheLimeGlass** [comment]
Fixed in 1.9.10
