### ISSUE TITLE
"Add page" does not work (?)

### ISSUE THREAD

**Issue by Damien0503** [TheLimeGlass/Skellett#99]
Hello, 

I find an issue concerning the "add page" syntax in the book feature. It's seems that it's not properly recognized.
Here is a screen : http://prntscr.com/t8i0al
And the result in the book : http://prntscr.com/t8i1md

I just took the example here : https://www.spigotmc.org/resources/skript-java-addon-skellett.34361/update?update=165758

**Comment by TheLimeGlass** [comment]
Book were removed from Skellett awhile ago. You can use vanilla Skript to add pages https://skriptlang.github.io/Skript/expressions.html#ExprBookPages
